### ISSUE TITLE
Invalid entry for production year

### ISSUE THREAD

**Issue by 3ll3d00d** [bmiller/miniDSPBEQ#1]
https://github.com/bmiller/miniDSPBEQ/blob/54755482726b1146f9adbdfa5018a49bd7c64961/Movie%20BEQs/Dolby%20Amaze%20(Regular)%20BEQ%20Atmos.xml#L1421

also in 

https://github.com/bmiller/miniDSPBEQ/blob/54755482726b1146f9adbdfa5018a49bd7c64961/Movie%20BEQs/Dolby%20Amaze%20(Loud)%20(%2B10%20gain)%20BEQ%20Atmos.xml#L1421

**Comment by bmiller** [comment]
Gah, just saw this.  I'm not getting email notifications on this repo for some reason.  Need to check that out.  Fixed now.
